### ISSUE TITLE
compile handshake.cc error

### ISSUE THREAD

**Issue by cokeBeer** [mykter/afl-training#21]
when compile target in heartbleed by
```
AFL_USE_ASAN=1 afl-clang-fast++ -g handshake.cc openssl/libssl.a openssl/libcrypto.a -o handshake -I openssl/include -ldl
```
I got
![image](https://user-images.githubusercontent.com/70683161/202895984-fcb71887-b368-4603-8b85-7883f55e3349.png)
I looked at the source code of handshake.cc, there does not exist identifier data or size.
How can I do to fix this?

**Comment by mykter** [comment]
Hi, the intent here is that you fill in the missing code:
```
/* TODO: To spoof one end of the handshake, we need to write data to sinbio
   * here */
 ```

You can find guidance on what code you need in HINTS.md and a complete solution in ANSWERS.md.
